### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/clickatell#1]
Let me know when you're done creating this package. Then I'll do a code review.

**Comment by freekmurze** [comment]
Code review done, if I've done anything you don't like, let me know.

**Comment by etiennemarais** [comment]
Thank you for the code review, there are a couple of problems I'd like to address, I will get to it today I promise

**Comment by etiennemarais** [comment]
Thanks, I am learning a lot as I go. I have to add better docs still and add tests for the actual `ClickatellClient`. I also want to add methods to handle retries somewhere, maybe you can give me some advise on that? I also need to fix the tests for the 5.6 php travis build.
