### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/clickatell#29]

**Comment by etiennemarais** [comment]
Please feel free to open a pull request to add support here if you require it. I think it's the perfect opportunity to add value to more people and contribute.

**Comment by atymic** [comment]
I actually manage the channels, sorry, probably should have linked back to the main issue:
https://github.com/laravel-notification-channels/channels/issues/90

Just creating issues so I can keep track of what needs upgrading :)

**Comment by etiennemarais** [comment]
Oh right, sorry. As you were XD

**Comment by atymic** [comment]
Closed in #30
