### ISSUE TITLE
Do not include user specific files in your .gitignore

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/clickatell#8]
Insights is complaining about the contents of .gitignore https://insight.sensiolabs.com/projects/853ee111-4bcf-4955-842c-dcd666da77a1/analyses/14

It's consider best practice to add a directory like `.idea` in a global .gitignore file. Some more info here: https://murze.be/2014/12/create-a-global-gitignore/

Could you remove `.idea` from `.gitignore`?

**Comment by etiennemarais** [comment]
Yes I understand, I will remove it

**Comment by etiennemarais** [comment]
👍  done

**Comment by freekmurze** [comment]
Thanks!!
